@host = localhost:8080

POST http://{{host}}/api/donations/create HTTP/1.1
content-type: application/json

{
    "From" : "Test of wallet creation",
	"ToStreamer" : "VovaPain",
	"Message": "hope it works",
	"Coin":"ton",
	"Amount" : 0.1712,      
	"Status": 1
}	