@host = localhost:8080

POST  http://{{host}}/api/publicregister HTTP/1.1
content-type: application/json

{
    "Nickname":    "Stray229",
	"name":        "Oleg",
	"Email":       "228@mail.com",
	"Youtube":     "kein",
	"Telegram":    "telegram.com/stra28882",
	"Password":    "pkkkkks"

}