@host = localhost:8080

POST http://{{host}}/api/donations/create HTTP/1.1
content-type: application/json

{
    "From" : "flö",
	"ToStreamer" : "VovaPain",
	"Message": "Final Donation system test",
	"Coin":"eth",
	"Amount" : 1.1,      
	"Status": 1
}	