@host = localhost:8080

POST http://{{host}}/api/donations/create HTTP/1.1
content-type: application/json

{
    "From" : "JOHNNY",
	"ToStreamer" : "VovaPain",
	"Message": "POKAZHI ZHOPU!!!!",
	"Coin":"btc",
	"Amount" : -1.3404,      
	"Status": 1
}	