@host = localhost:8080

//Register with full info aka KYC
 POST http://{{host}}/api/user/register/streamer/full HTTP/1.1
content-type: application/json

{
    "Nickname" : "Stray228",
    "Description" : "Любитель конфет, а также АСУ АСУ ракет",
    "Telegram": "t.me/StrayDungeon228",
    "Youtube" : "youtube.com/c/StrayBest",
    "Twitch": "twitch.tv/stray228"
}
