@host = localhost:8080

//Register with full info aka KYC
 POST http://{{host}}/api/user/register/streamer/full HTTP/1.1
content-type: application/json

{
    "Nickname" : "VovaPain",
    "Description" : "Самый лучший солевой стример на планете ЗЕМЛЯ ",
    "Telegram": "Test Telegram",
    "Youtube" : "Test Youtube",
    "Twitch": "Test Twitch"
}
